# Generated by Django 3.1.3 on 2020-12-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worktable',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('job', models.IntegerField(db_column='job', default=0)),
                ('team', models.CharField(db_column='team', max_length=255)),
                ('rep', models.CharField(db_column='rep', max_length=255)),
                ('description', models.TextField(db_column='description')),
                ('remark', models.TextField(db_column='remark')),
            ],
            options={
                'db_table': 'work',
                'managed': False,
            },
        ),
    ]
