# Generated by Django 3.1.3 on 2020-12-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='worktable',
            table='worktable',
        ),
    ]
