# Generated by Django 3.1.3 on 2020-12-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_auto_20201224_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False)),
                ('job', models.IntegerField(db_column='job', default=0)),
                ('team', models.CharField(db_column='team', max_length=255)),
                ('rep', models.CharField(db_column='rep', max_length=255)),
                ('description', models.TextField(db_column='description')),
            ],
        ),
    ]
