# Generated by Django 3.1.3 on 2020-12-27 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
