# Generated by Django 3.1.3 on 2021-01-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('roomname', models.CharField(max_length=45)),
                ('roomno', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('usersid', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
                ('userteam', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('useremail', models.CharField(max_length=128)),
                ('auth', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
